### ISSUE TITLE
Server advert

### ISSUE THREAD

**Issue by naxed** [naxed/gtaFiveM#25]
Feature pour rajouter des messages sur le serveur
https://forum.fivem.net/t/release-server-adverts-1-0/17535

**Comment by naxed** [comment]
A pusher en prod ce soir, voir pour rajouter des messages

**Comment by Xtrem65** [comment]
=> Ajouter un message indiquant que nous sommes ouverts à toute proposition d'équilibrage ingame.

"Vous trouvez qu'il est trop facile d'effectuer une mission de tueur à gages ? trop dur de blanchir de l'argent ? N’hésitez pas a donner votre avis sur le forum !"

**Comment by naxed** [comment]
Done
