### ISSUE TITLE
Killer: faire avertir les flics plus tot

### ISSUE THREAD

**Issue by naxed** [naxed/gtaFiveM#4]

**Comment by Xtrem65** [comment]
Plus fonctionnel suite au changement de mod police

**Comment by Xtrem65** [comment]
Prêt à merger

**Comment by Xtrem65** [comment]
Bug sur récupération cop en lignes => Nécessite redémarrage de serveur.
Bug sur Marqueur Info Meurtres => Accessible aux joueurs non policiers ?
Bug sur Date de la mort => Synchronisation entre joueurs
